### ISSUE TITLE
我之前有想法把这个做成一个应用...

### ISSUE THREAD

**Issue by SergioChan** [wendzhue/skill-tree-dev#1]
对于全栈来说技能树是很重要的东西, 对于职业选择和发展都很有帮助, 之前也想做, 但是一个是只局限于程序员好么? 如何定义正确的发展的路线...最重要的是, 靠什么圈子让程序员都开始用这个技能树来帮助自己的规划..挺多问题的, 当时就搁置了... 你有什么其他的角度么

**Comment by wendzhue** [comment]
我想过技能树会涉及到哪些行业或者岗位，还是先从程序员做起吧，程序员也分很多种，内容会比较丰富，那些 CS 专业的大学生也最可能用。

不知道你有没有看过一个 web 开发的技能树，我推荐给我一个北邮的同学，他马上就喜欢上了。我觉得这个可以做到自传播的。

**Comment by SergioChan** [comment]
@wendzhue 之前nodex上面看过,挺想做的,你有好的设计方案么,客户端或者web的都可以

**Comment by wendzhue** [comment]
@SergioChan 应该是要做 web 端的，怎么做我还没有想好，最近实习有点忙。下一周我会好好想想，先出个信息结构图之类的。
